packages = [
  "espanso",
  "fish",
  "ghostty",
  "git",
  "kitty",
  "lazygit",
  "mpv",
  "nvim",
  "opencode",
  "scripts",
  "starship",
  "systemd",
  "tmux",
  "vscode",
  "wezterm",
  "yazi",
]
