[settings]
default_target_type = "symbolic"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
"git/gitui" = "~/.config/gitui"

[fish.files]
"fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

# Terminals
[ghostty.files]
"ghostty" = { target = "~/.config/ghostty", type = "symbolic", recurse = false }

[kitty.files]
"kitty" = { target = "~/.config/kitty", type = "symbolic", recurse = false }

[wezterm.files]
"wezterm" = { target = "~/.config/wezterm", type = "symbolic", recurse = false }

[tmux.files]
"tmux" = { target = "~/.config/tmux", type = "symbolic", recurse = false }

# Editors
[nvim.files]
"nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

# Scripts
[scripts.files]
"scripts" = "~/.config/scripts"

# tools
[yazi.files]
"yazi" = { target = "~/.config/yazi", type = "symbolic", recurse = false }

[mpv.files]
"mpv" = { target = "~/.config/mpv", type = "symbolic", recurse = false }

[lazygit.files]
"lazygit" = { target = "~/.config/lazygit", type = "symbolic", recurse = false }

[lf.files]
"lf" = { target = "~/.config/lf", type = "symbolic", recurse = false }

[vscode.files]
"vscode/settings.json" = "~/.config/Code/User/settings.json"
"vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"

# systemd
[systemd.files]
"systemd" = "~/.config/systemd"
